spring:
  application:
    name: Ludotheque
  config:
    import:
      - optional:file:./config/application-local.yaml

  #Connection to DB
  datasource:
    url: ${app.db.url}
    username: ${app.db.user}
    password: ${app.db.password}

  #Options to DB
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create